### ISSUE TITLE
When using subscription, TotalCountPaginationExtension module makes error.

### ISSUE THREAD

**Issue by fingul** [m4riok/strawberry-django-extras#4]
Hello! Thank you for your great work.

When using "TotalCountPaginationExtension" module, 

setup subscription using  [this](https://strawberry-graphql.github.io/strawberry-django/guide/subscriptions/#subscriptions) docs. ( https://strawberry-graphql.github.io/strawberry-django/guide/subscriptions/#subscriptions )

Then, strawberry_django_extras.decorators.is_async returns False.

But, it need return True. 

Eventually, "You cannot call this from an async context - use a thread or sync_to_async." exception occur.

Please, check this. Thank you. Have a good day.

**Comment by m4riok** [comment]
Hello @fingul.

`strawberry_django_extras.decorators.is_async` simply checks if you are running within an event loop. 

```python
def is_async() -> bool:
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return False
    else:
        return True
```

If you aren't running within an event loop it's likely because at some point in the execution chain your code has already been wrapped with `@sync_to_async` either because you wrapped it or some other extension you are using did. Keep in mind extension order matters. 

Please provide some snippets on how you are using the extension , your complete traceback and some more information on how you are running your app ( fe unicorn , daphne ? ) so I can replicate the issue because I cannot seem to get a replication of the issue. 

Thanks for reporting this.
